//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTester.HelloService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloService.IHelloService")]
    public interface IHelloService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/SayHello", ReplyAction="http://tempuri.org/IHelloService/SayHelloResponse")]
        string SayHello(string name, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/Zbir", ReplyAction="http://tempuri.org/IHelloService/ZbirResponse")]
        int Zbir(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/Razlika", ReplyAction="http://tempuri.org/IHelloService/RazlikaResponse")]
        int Razlika(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/Proizvod", ReplyAction="http://tempuri.org/IHelloService/ProizvodResponse")]
        int Proizvod(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/Kolicnik", ReplyAction="http://tempuri.org/IHelloService/KolicnikResponse")]
        double Kolicnik(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/AllArchParks", ReplyAction="http://tempuri.org/IHelloService/AllArchParksResponse")]
        string AllArchParks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/AllParkObjects", ReplyAction="http://tempuri.org/IHelloService/AllParkObjectsResponse")]
        string AllParkObjects(string park_name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelloServiceChannel : ServiceTester.HelloService.IHelloService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloServiceClient : System.ServiceModel.ClientBase<ServiceTester.HelloService.IHelloService>, ServiceTester.HelloService.IHelloService {
        
        public HelloServiceClient() {
        }
        
        public HelloServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SayHello(string name, string language) {
            return base.Channel.SayHello(name, language);
        }
        
        public int Zbir(int a, int b) {
            return base.Channel.Zbir(a, b);
        }
        
        public int Razlika(int a, int b) {
            return base.Channel.Razlika(a, b);
        }
        
        public int Proizvod(int a, int b) {
            return base.Channel.Proizvod(a, b);
        }
        
        public double Kolicnik(int a, int b) {
            return base.Channel.Kolicnik(a, b);
        }
        
        public string AllArchParks() {
            return base.Channel.AllArchParks();
        }
        
        public string AllParkObjects(string park_name) {
            return base.Channel.AllParkObjects(park_name);
        }
    }
}
